
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.Socket;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Bill extends javax.swing.JFrame {

    private Socket sc;
    private DataOutputStream out=null;
    private DataInputStream in=null;
    private String pid;
    private String quantity;
    private InputStream inputStream = null;
    AfterLogin obj=null;
    
    public Bill() {
        initComponents();
    }
    public Bill(AfterLogin af,Socket sc,String qty,String pid) throws IOException
    {
        initComponents();
        this.sc=sc;
        this.pid=pid;
        this.obj=af;
        this.quantity=qty;
        try {
            
            out = new DataOutputStream(sc.getOutputStream());
            in=new DataInputStream(sc.getInputStream());
        
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,"Error in Bill Constructor");
        }
        System.out.println("1");
        out.writeUTF("req@showbill");
        out.writeUTF(pid);
        out.writeUTF(qty);
        String offer=in.readUTF();
        String status=in.readUTF();
        if(status.equals("success"))
        {
            
            String name=in.readUTF();
            String reference=in.readUTF();
            String date=in.readUTF();
            String quantity=in.readUTF();
            String cost=in.readUTF();

            Product.setText("Product Name :"+name);
            RefNo.setText("Referenece Number :ref#1A01"+reference);
            dt.setText("Date and Time :" +date);
            qt.setText("Quantity :"+quantity);
            Price.setText("Total cost spent :"+cost);
            if(offer.equals("yes"))
                 addoffer.setText("Additional Offer : 15%");
            else
                addoffer.setText("No Additional offer applicable");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Insufficient Inventory");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Product = new javax.swing.JLabel();
        RefNo = new javax.swing.JLabel();
        dt = new javax.swing.JLabel();
        qt = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        addoffer = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Your Bill");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 33, 190, 51));

        Product.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Product.setForeground(new java.awt.Color(255, 255, 255));
        Product.setText("Product Name");
        getContentPane().add(Product, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 97, 246, 26));

        RefNo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        RefNo.setForeground(new java.awt.Color(255, 255, 255));
        RefNo.setText("Reference Number");
        getContentPane().add(RefNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 141, 246, 27));

        dt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        dt.setForeground(new java.awt.Color(255, 255, 255));
        dt.setText("Date and Time");
        getContentPane().add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 181, 246, 28));

        qt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        qt.setForeground(new java.awt.Color(255, 255, 255));
        qt.setText("Quantity ");
        getContentPane().add(qt, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 222, 246, 27));

        Price.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Price.setForeground(new java.awt.Color(255, 255, 255));
        Price.setText("Total Price Paid ");
        getContentPane().add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 262, 246, 24));

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        addoffer.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addoffer.setForeground(new java.awt.Color(255, 255, 255));
        addoffer.setText("Additional Offer");
        getContentPane().add(addoffer, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 304, 246, 28));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sacredbaazar/Bill.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Product;
    private javax.swing.JLabel RefNo;
    private javax.swing.JLabel addoffer;
    private javax.swing.JLabel dt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel qt;
    // End of variables declaration//GEN-END:variables
}
